---
- name: Kullanici gruplari kontrol ediliyor.
  group:
        name: "{{ item.value.name }}"
        state: "{{ item.value.state }}"
  with_dict: "{{ base_user_groups }}"
  sudo: yes
  tags: group
