---
- name: Base rolu icin gerekli paketler yukleniyor.
  apt:
        name: "{{ item.value.name }}"
        state: "{{ item.value.state }}"
        force: "yes"
  with_dict: "{{base_packages}}"
  sudo: yes
  tags: install
