---
- name: Ahtapot icin gerekli depo yukleniyor.
  apt_repository:
        repo: "{{ item.value.url }}"
        update_cache: "{{ item.value.updatecache }}"
        state: "{{ item.value.state }}"
  with_dict: "{{base_repositories}}"
  sudo: yes
  tags: repo
