---
# Auditd degiskenlerini iceren dosyadir.
audit:
    conf:
        source: "auditd.conf.j2"
        destination: "/etc/audit/auditd.conf"
        owner: "root"
        group: "root"
        mode: "0644"
    service:
        name: "auditd"
        state: "started"
        enabled: "yes"
    rules:
        source: "audit.rules.j2"
        destination: "/etc/audit/rules.d/ahtapot-audit.rules"
        owner: "root"
        group: "root"
        mode: "0644"
    name: "ahtapotops"
    name_format: "user"
    log_file: "/var/log/audit/audit.log"
    log_format: "RAW"
    log_group: "root"
    max_log_file: "30"
    max_log_file_action: "keep_logs"
    num_logs: "5"
    priority_boost: "4"
    flush: "INCREMENTAL"
    freq: "20"
    disp_qos: "lossy"
    dispatcher: "/sbin/audispd"
    space_left: "2000"
    space_left_action: "email"
    action_mail_acct: "root"
    admin_space_left: "1000"
    admin_space_left_action: "halt"
    disk_full_action: "SUSPEND"
    disk_error_action: "SUSPEND"
    tcp_listen_queue: "5"
    tcp_max_per_addr: "1"
    tcp_client_ports: "1024-65535"
    tcp_client_max_idle: "0"
    enable_krb5: "no"
    krb5_principal: "auditd"
    krb5_key_file: "/etc/audit/audit.key"
